<?php

namespace Database\Seeders;

use App\Enums\ActiveStatus;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = date('Y-m-d H:i:s');
        $data = [
            ['name' => 'iPhone 11 Pro Max 64GB',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 10',
            'ram' => ' 4GB',
            'rom' => ' 64GB',
            'battery_capacity' => ' 3046 mAh',
            'front_camera' => ' 12MP',
            'rear_camera' => ' 3 camera 12 MP',
            'price' =>'300',
            'color' =>'Black',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 1',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'Samsung Galaxy S20+',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 20',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4500 mAh',
            'front_camera' => ' 10MP',
            'rear_camera' => ' Chính 12 MP & Phụ 64 MP, 12 MP, TOF 3D',
            'price' =>'400',
            'color' => 'Silver',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 2',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => ' OPPO Find X2',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 70',
            'ram' => ' 12GB',
            'rom' => ' 256GB',
            'battery_capacity' => ' 4200 mAh',
            'front_camera' => ' 32MP',
            'rear_camera' => ' Chính 48 MP & Phụ 13 MP, 12 MP',
            'price' =>'600',
            'color' => 'Blue',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 3',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => ' OPPO A93  ',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 70',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4000 mAh',
            'front_camera' => ' Chính 16 MP & Phụ 2 MP',
            'rear_camera' => ' Chính 48 MP & Phụ 8 MP, 2 MP, 2 MP',
            'price' =>'600',
            'color' => 'Blue',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 3',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'iPhone 12 64GB',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 10',
            'ram' => ' 4GB',
            'rom' => ' 64GB',
            'battery_capacity' => ' 2815 mAh',
            'front_camera' => ' 12MP',
            'rear_camera' => ' 2 camera 12 MP',
            'price' =>'300',
            'color' =>'Black',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 1',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'iPhone 12 Pro Max 128GB',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 10',
            'ram' => ' 4GB',
            'rom' => ' 64GB',
            'battery_capacity' => ' 2815 mAh',
            'front_camera' => ' 12MP',
            'rear_camera' => ' 2 camera 12 MP',
            'price' =>'600',
            'color' =>'Black',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 1',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'iPhone SE 128GB',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 10',
            'ram' => ' 4GB',
            'rom' => ' 64GB',
            'battery_capacity' => ' 2815 mAh',
            'front_camera' => ' 12MP',
            'rear_camera' => ' 2 camera 12 MP',
            'price' =>'600',
            'color' =>'Black',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 1',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'iPhone XR 128GB',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 50',
            'ram' => ' 4GB',
            'rom' => ' 64GB',
            'battery_capacity' => ' 2815 mAh',
            'front_camera' => ' 12MP',
            'rear_camera' => ' 2 camera 12 MP',
            'price' =>'600',
            'color' =>'Black',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 1',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'Samsung Galaxy A02',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 20',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4500 mAh',
            'front_camera' => ' 10MP',
            'rear_camera' => ' Chính 12 MP & Phụ 64 MP, 12 MP, TOF 3D',
            'price' =>'400',
            'color' => 'Silver',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 2',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'Samsung Galaxy M51',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 20',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4500 mAh',
            'front_camera' => ' 10MP',
            'rear_camera' => ' Chính 12 MP & Phụ 64 MP, 12 MP, TOF 3D',
            'price' =>'400',
            'color' => 'Silver',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 2',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'Samsung Galaxy Z Fold2 5G',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 20',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4500 mAh',
            'front_camera' => ' 10MP',
            'rear_camera' => ' Chính 12 MP & Phụ 64 MP, 12 MP, TOF 3D',
            'price' =>'400',
            'color' => 'Silver',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 2',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => 'Samsung Galaxy Note 20 Ultra 5G',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 20',
            'ram' => ' 8GB',
            'rom' => ' 128GB',
            'battery_capacity' => ' 4500 mAh',
            'front_camera' => ' 10MP',
            'rear_camera' => ' Chính 12 MP & Phụ 64 MP, 12 MP, TOF 3D',
            'price' =>'400',
            'color' => 'Silver',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 2',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => ' OPPO A94',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 70',
            'ram' => ' 12GB',
            'rom' => ' 256GB',
            'battery_capacity' => ' 4200 mAh',
            'front_camera' => ' 32MP',
            'rear_camera' => ' Chính 48 MP & Phụ 13 MP, 12 MP',
            'price' =>'600',
            'color' => 'Blue',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 3',
            'created_at' => $date,
            'updated_at' => $date,],
            ['name' => ' OPPO Reno5',
            'description' => ' Smart Phone',
            'quantityInStore' => ' 70',
            'ram' => ' 12GB',
            'rom' => ' 256GB',
            'battery_capacity' => ' 4200 mAh',
            'front_camera' => ' 32MP',
            'rear_camera' => ' Chính 48 MP & Phụ 13 MP, 12 MP',
            'price' =>'600',
            'color' => 'Blue',
            'status' => ActiveStatus::ACTIVE,
            'category_id' => ' 3',
            'created_at' => $date,
            'updated_at' => $date,],
        ];
        DB::table('products')->insert($data);
    }
}
